export default [
  'candidateGenerationState',
  'channelClose',
  'channelError',
//  'channelMessage',
  'channelOpen',
  'channelRetry',
//  'dataChannelState',
  'dataTransferState',
  'getPeersStateChange',
  //'handshakeProgress',
//  'iceConnectionState',
  'incomingData',
  'incomingDataRequest',
  'incomingMessage',
  'incomingStream',
  'introduceStateChange',
  'mediaAccessError',
  'mediaAccessFallback',
  'mediaAccessRequired',
  'mediaAccessStopped',
  'mediaAccessSuccess',
//  'peerConnectionState',
  'peerJoined',
  'peerLeft',
  'peerRestart',
  'peerUpdated',
  'readyStateChange',
  'roomLock',
  'serverPeerJoined',
  'serverPeerLeft',
  'serverPeerRestart',
  'socketError',
  'streamEnded',
  'streamMuted',
  'systemAction'
]
